In [2]:
import pandas as pd
df=pd.read_csv('covid_toy.csv')
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop('has_covid',axis=1),df['has_covid'],test_size=0.2,random_state=0)
X_train.shape,X_test.shape

((80, 5), (20, 5))

# Manual Preprocessing of data

### Treating null values

In [3]:

df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
from sklearn.impute import SimpleImputer
si=SimpleImputer()
si.fit(X_train[['fever']])
X_train_fever=si.transform(X_train[['fever']])
X_test_fever=si.transform(X_test[['fever']])

0    0
dtype: int64

### Treating Categorical values

In [21]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Mild','Strong']])
oe.fit(X_train[['cough']])
X_train_cough=oe.transform(X_train[['cough']])
X_test_cough=oe.transform(X_test[['cough']])

In [22]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False)
ohe.fit(X_train[['gender','city']])
X_train_gender_city=ohe.transform(X_train[['gender','city']])
X_test_gender_city=ohe.transform(X_test[['gender','city']])

### Extracting age

In [23]:
X_train_age=X_train.drop(columns=['gender','fever','cough','city'])
X_test_age=X_test.drop(columns=['gender','fever','cough','city'])

### Concatenating data columnns

In [25]:
import numpy as np
X_train_trf=np.concatenate((X_train_age,X_train_gender_city,X_train_cough,X_train_fever),axis=1)
X_test_trf=np.concatenate((X_test_age,X_test_gender_city,X_test_cough,X_test_fever),axis=1)
X_train_trf=pd.DataFrame(X_train_trf)
X_train_trf

       0    1    2    3    4    5      6
0   22.0  0.0  0.0  0.0  0.0  0.0   99.0
1   56.0  0.0  0.0  0.0  0.0  1.0  104.0
2   31.0  0.0  0.0  1.0  0.0  0.0   98.0
3   75.0  0.0  1.0  0.0  0.0  1.0  104.0
4   72.0  1.0  0.0  0.0  0.0  0.0   99.0
..   ...  ...  ...  ...  ...  ...    ...
75  51.0  0.0  0.0  1.0  0.0  1.0  101.0
76  65.0  1.0  0.0  0.0  0.0  0.0   99.0
77  42.0  1.0  0.0  0.0  1.0  0.0  104.0
78  18.0  0.0  0.0  0.0  0.0  0.0  104.0
79  20.0  1.0  1.0  0.0  0.0  1.0  102.0

[80 rows x 7 columns]