In [2]:
import pandas as pd
df=pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop('has_covid',axis=1),df['has_covid'],test_size=0.2,random_state=0)
X_train.shape,X_test.shape

((80, 5), (20, 5))

# Using column transformer

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
trf=ColumnTransformer(transformers=[
    ('trf1',SimpleImputer(),['fever']),
    ('trf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('trf3',OneHotEncoder(drop='first'),['gender','city'])
    
],remainder='passthrough')

In [15]:
trf.fit(X_train)
X_train_trf_1=trf.transform(X_train)
X_test_trf_1=trf.transform(X_test)
X_train_trf_1=pd.DataFrame(X_train_trf_1)
X_train_trf_1

        0    1    2    3    4    5
0    99.0  0.0  0.0  0.0  0.0  0.0
1   104.0  1.0  0.0  0.0  0.0  0.0
2    98.0  0.0  0.0  0.0  1.0  0.0
3   104.0  1.0  0.0  1.0  0.0  0.0
4    99.0  0.0  1.0  0.0  0.0  0.0
..    ...  ...  ...  ...  ...  ...
75  101.0  1.0  0.0  0.0  1.0  0.0
76   99.0  0.0  1.0  0.0  0.0  0.0
77  104.0  0.0  1.0  0.0  0.0  1.0
78  104.0  0.0  0.0  0.0  0.0  0.0
79  102.0  1.0  1.0  1.0  0.0  0.0

[80 rows x 6 columns]